# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fraccalc', [dirname(__file__)])
        except ImportError:
            import _fraccalc
            return _fraccalc
        if fp is not None:
            try:
                _mod = imp.load_module('_fraccalc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _fraccalc = swig_import_helper()
    del swig_import_helper
else:
    import _fraccalc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _fraccalc.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fraccalc.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(self, *args) -> "double" : return _fraccalc.doubleArray___getitem__(self, *args)
    def __setitem__(self, *args) -> "void" : return _fraccalc.doubleArray___setitem__(self, *args)
    def cast(self) -> "double *" : return _fraccalc.doubleArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _fraccalc.doubleArray_frompointer
    if _newclass:frompointer = staticmethod(_fraccalc.doubleArray_frompointer)
doubleArray_swigregister = _fraccalc.doubleArray_swigregister
doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(*args) -> "doubleArray *" :
  return _fraccalc.doubleArray_frompointer(*args)
doubleArray_frompointer = _fraccalc.doubleArray_frompointer


def Init(*args) -> "int" :
  return _fraccalc.Init(*args)
Init = _fraccalc.Init

def Finish() -> "int" :
  return _fraccalc.Finish()
Finish = _fraccalc.Finish

def set_xData(*args) -> "void" :
  return _fraccalc.set_xData(*args)
set_xData = _fraccalc.set_xData

def set_yData(*args) -> "void" :
  return _fraccalc.set_yData(*args)
set_yData = _fraccalc.set_yData

def set_zData(*args) -> "void" :
  return _fraccalc.set_zData(*args)
set_zData = _fraccalc.set_zData

def getN(*args) -> "int" :
  return _fraccalc.getN(*args)
getN = _fraccalc.getN
# This file is compatible with both classic and new-style classes.


