//
// Created by joao on 25/06/2021.
//

#define NK_IMPLEMENTATION
#define NK_SFML_IMPLEMENTATION



#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT

#include "_nuklear.h"
#include "_nuklear_sfml.hpp"
