authors = ["Fernando Miguel Hahne <fernandomhahne@gmail.com>"]
name = "Compactons"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
