#!/usr/bin/env python
# -*- coding: utf-8 -*-

import EnergyPlotting

if __name__ == '__main__':
    try:
        parser = EnergyPlotting.GET_ENERGY_CALC_ARGUMENTS()
        outputFileName = EnergyPlotting.ComputeEnergyMap(parser)
    except Exception:
        print("Error: " + Exception.args)
        exit(-1)


