# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigator.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 1038)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sptMainPlotNavPlot = QtWidgets.QSplitter(self.centralwidget)
        self.sptMainPlotNavPlot.setOrientation(QtCore.Qt.Horizontal)
        self.sptMainPlotNavPlot.setObjectName("sptMainPlotNavPlot")
        self.wgtMainMatplot = QSimPlot(self.sptMainPlotNavPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtMainMatplot.sizePolicy().hasHeightForWidth())
        self.wgtMainMatplot.setSizePolicy(sizePolicy)
        self.wgtMainMatplot.setMinimumSize(QtCore.QSize(512, 0))
        self.wgtMainMatplot.setBaseSize(QtCore.QSize(0, 0))
        self.wgtMainMatplot.setAutoFillBackground(False)
        self.wgtMainMatplot.setProperty("hasToolbar", True)
        self.wgtMainMatplot.setObjectName("wgtMainMatplot")
        self.sptNavPlotInfo = QtWidgets.QSplitter(self.sptMainPlotNavPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sptNavPlotInfo.sizePolicy().hasHeightForWidth())
        self.sptNavPlotInfo.setSizePolicy(sizePolicy)
        self.sptNavPlotInfo.setOrientation(QtCore.Qt.Vertical)
        self.sptNavPlotInfo.setObjectName("sptNavPlotInfo")
        self.frmNavigatorPlot = QtWidgets.QFrame(self.sptNavPlotInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frmNavigatorPlot.sizePolicy().hasHeightForWidth())
        self.frmNavigatorPlot.setSizePolicy(sizePolicy)
        self.frmNavigatorPlot.setMinimumSize(QtCore.QSize(320, 320))
        self.frmNavigatorPlot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmNavigatorPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmNavigatorPlot.setLineWidth(1)
        self.frmNavigatorPlot.setObjectName("frmNavigatorPlot")
        self.lytNavigatorPlot = QtWidgets.QVBoxLayout(self.frmNavigatorPlot)
        self.lytNavigatorPlot.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lytNavigatorPlot.setContentsMargins(2, 2, 3, 2)
        self.lytNavigatorPlot.setSpacing(0)
        self.lytNavigatorPlot.setObjectName("lytNavigatorPlot")
        self.wgtNavigatorPlot = QParamPlot(self.frmNavigatorPlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.wgtNavigatorPlot.sizePolicy().hasHeightForWidth())
        self.wgtNavigatorPlot.setSizePolicy(sizePolicy)
        self.wgtNavigatorPlot.setMinimumSize(QtCore.QSize(256, 256))
        self.wgtNavigatorPlot.setMaximumSize(QtCore.QSize(1024, 1024))
        self.wgtNavigatorPlot.setSizeIncrement(QtCore.QSize(0, 0))
        self.wgtNavigatorPlot.setBaseSize(QtCore.QSize(256, 256))
        self.wgtNavigatorPlot.setObjectName("wgtNavigatorPlot")
        self.lytNavigatorPlot.addWidget(self.wgtNavigatorPlot)
        self.frmInfo = QtWidgets.QFrame(self.sptNavPlotInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frmInfo.sizePolicy().hasHeightForWidth())
        self.frmInfo.setSizePolicy(sizePolicy)
        self.frmInfo.setMinimumSize(QtCore.QSize(300, 256))
        self.frmInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInfo.setObjectName("frmInfo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmInfo)
        self.verticalLayout_2.setContentsMargins(-1, 8, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grpNavInfo = QtWidgets.QGroupBox(self.frmInfo)
        self.grpNavInfo.setObjectName("grpNavInfo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grpNavInfo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.grdV = QtWidgets.QGridLayout()
        self.grdV.setObjectName("grdV")
        self.sldVValue = QtWidgets.QLabel(self.grpNavInfo)
        self.sldVValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sldVValue.setText("")
        self.sldVValue.setObjectName("sldVValue")
        self.grdV.addWidget(self.sldVValue, 0, 2, 1, 1)
        self.sldV = QtWidgets.QSlider(self.grpNavInfo)
        self.sldV.setOrientation(QtCore.Qt.Horizontal)
        self.sldV.setObjectName("sldV")
        self.grdV.addWidget(self.sldV, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grdV.addItem(spacerItem, 0, 1, 1, 1)
        self.lblV = QtWidgets.QLabel(self.grpNavInfo)
        self.lblV.setObjectName("lblV")
        self.grdV.addWidget(self.lblV, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.grdV)
        self.grdv = QtWidgets.QGridLayout()
        self.grdv.setObjectName("grdv")
        self.sldvValue = QtWidgets.QLabel(self.grpNavInfo)
        self.sldvValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sldvValue.setText("")
        self.sldvValue.setObjectName("sldvValue")
        self.grdv.addWidget(self.sldvValue, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grdv.addItem(spacerItem1, 0, 1, 1, 1)
        self.lblv = QtWidgets.QLabel(self.grpNavInfo)
        self.lblv.setObjectName("lblv")
        self.grdv.addWidget(self.lblv, 0, 0, 1, 1)
        self.sldv = QtWidgets.QSlider(self.grpNavInfo)
        self.sldv.setOrientation(QtCore.Qt.Horizontal)
        self.sldv.setObjectName("sldv")
        self.grdv.addWidget(self.sldv, 1, 0, 1, 3)
        self.verticalLayout_4.addLayout(self.grdv)
        self.grdPhase = QtWidgets.QGridLayout()
        self.grdPhase.setObjectName("grdPhase")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grdPhase.addItem(spacerItem2, 0, 1, 1, 1)
        self.sldPhaseValue = QtWidgets.QLabel(self.grpNavInfo)
        self.sldPhaseValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sldPhaseValue.setText("")
        self.sldPhaseValue.setObjectName("sldPhaseValue")
        self.grdPhase.addWidget(self.sldPhaseValue, 0, 2, 1, 1)
        self.lblPhase = QtWidgets.QLabel(self.grpNavInfo)
        self.lblPhase.setObjectName("lblPhase")
        self.grdPhase.addWidget(self.lblPhase, 0, 0, 1, 1)
        self.sldPhase = QtWidgets.QSlider(self.grpNavInfo)
        self.sldPhase.setOrientation(QtCore.Qt.Horizontal)
        self.sldPhase.setObjectName("sldPhase")
        self.grdPhase.addWidget(self.sldPhase, 1, 0, 1, 3)
        self.verticalLayout_4.addLayout(self.grdPhase)
        self.verticalLayout_2.addWidget(self.grpNavInfo)
        self.grpRender = QtWidgets.QGroupBox(self.frmInfo)
        self.grpRender.setObjectName("grpRender")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grpRender)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkLogScale = QtWidgets.QCheckBox(self.grpRender)
        self.chkLogScale.setMinimumSize(QtCore.QSize(0, 0))
        self.chkLogScale.setChecked(True)
        self.chkLogScale.setObjectName("chkLogScale")
        self.horizontalLayout_3.addWidget(self.chkLogScale)
        self.label = QtWidgets.QLabel(self.grpRender)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.epsilonSpinBox = QtWidgets.QDoubleSpinBox(self.grpRender)
        self.epsilonSpinBox.setDecimals(3)
        self.epsilonSpinBox.setMinimum(-10.0)
        self.epsilonSpinBox.setMaximum(-1.0)
        self.epsilonSpinBox.setSingleStep(0.1)
        self.epsilonSpinBox.setProperty("value", -6.0)
        self.epsilonSpinBox.setObjectName("epsilonSpinBox")
        self.horizontalLayout_3.addWidget(self.epsilonSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.grpRender)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.widthSpinBox = QtWidgets.QSpinBox(self.grpRender)
        self.widthSpinBox.setMinimum(768)
        self.widthSpinBox.setMaximum(4096)
        self.widthSpinBox.setProperty("value", 1024)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.horizontalLayout_4.addWidget(self.widthSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.grpRender)
        spacerItem3 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.grpNavInfoOptions = QtWidgets.QGroupBox(self.frmInfo)
        self.grpNavInfoOptions.setObjectName("grpNavInfoOptions")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grpNavInfoOptions)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.chkSaveImage = QtWidgets.QCheckBox(self.grpNavInfoOptions)
        self.chkSaveImage.setChecked(True)
        self.chkSaveImage.setObjectName("chkSaveImage")
        self.verticalLayout_5.addWidget(self.chkSaveImage)
        self.chkRegenImg = QtWidgets.QCheckBox(self.grpNavInfoOptions)
        self.chkRegenImg.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.chkRegenImg.setAutoRepeatInterval(100)
        self.chkRegenImg.setObjectName("chkRegenImg")
        self.verticalLayout_5.addWidget(self.chkRegenImg)
        self.chkRegen = QtWidgets.QCheckBox(self.grpNavInfoOptions)
        self.chkRegen.setObjectName("chkRegen")
        self.verticalLayout_5.addWidget(self.chkRegen)
        self.chkPreferImage = QtWidgets.QCheckBox(self.grpNavInfoOptions)
        self.chkPreferImage.setChecked(True)
        self.chkPreferImage.setObjectName("chkPreferImage")
        self.verticalLayout_5.addWidget(self.chkPreferImage)
        self.chkAutoLoad = QtWidgets.QCheckBox(self.grpNavInfoOptions)
        self.chkAutoLoad.setObjectName("chkAutoLoad")
        self.verticalLayout_5.addWidget(self.chkAutoLoad)
        self.verticalLayout_2.addWidget(self.grpNavInfoOptions)
        self.btnGenerate = QtWidgets.QPushButton(self.frmInfo)
        self.btnGenerate.setObjectName("btnGenerate")
        self.verticalLayout_2.addWidget(self.btnGenerate)
        self.gridLayout.addWidget(self.sptMainPlotNavPlot, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 20))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dckHistoryPlot = QtWidgets.QDockWidget(MainWindow)
        self.dckHistoryPlot.setEnabled(True)
        self.dckHistoryPlot.setMinimumSize(QtCore.QSize(400, 392))
        self.dckHistoryPlot.setMaximumSize(QtCore.QSize(524287, 524286))
        self.dckHistoryPlot.setFloating(True)
        self.dckHistoryPlot.setObjectName("dckHistoryPlot")
        self.dckContainerHistory = QtWidgets.QWidget()
        self.dckContainerHistory.setObjectName("dckContainerHistory")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dckContainerHistory)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frmHistory = QtWidgets.QFrame(self.dckContainerHistory)
        self.frmHistory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmHistory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHistory.setObjectName("frmHistory")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frmHistory)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frmHistoryPlot = QtWidgets.QFrame(self.frmHistory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmHistoryPlot.sizePolicy().hasHeightForWidth())
        self.frmHistoryPlot.setSizePolicy(sizePolicy)
        self.frmHistoryPlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmHistoryPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHistoryPlot.setObjectName("frmHistoryPlot")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmHistoryPlot)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wgtHistoryPlot = QMatplotlibHistory(self.frmHistoryPlot)
        self.wgtHistoryPlot.setObjectName("wgtHistoryPlot")
        self.horizontalLayout_2.addWidget(self.wgtHistoryPlot)
        self.gridLayout_2.addWidget(self.frmHistoryPlot, 0, 2, 1, 1)
        self.frmHistoryOptions = QtWidgets.QVBoxLayout()
        self.frmHistoryOptions.setObjectName("frmHistoryOptions")
        self.lytSymmetryMode = QtWidgets.QGroupBox(self.frmHistory)
        self.lytSymmetryMode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lytSymmetryMode.setObjectName("lytSymmetryMode")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lytSymmetryMode)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbtT = QtWidgets.QRadioButton(self.lytSymmetryMode)
        self.rbtT.setChecked(True)
        self.rbtT.setProperty("modeLabel", "τ")
        self.rbtT.setObjectName("rbtT")
        self.verticalLayout.addWidget(self.rbtT)
        self.rbtX = QtWidgets.QRadioButton(self.lytSymmetryMode)
        self.rbtX.setProperty("modeLabel", "x")
        self.rbtX.setObjectName("rbtX")
        self.verticalLayout.addWidget(self.rbtX)
        self.frmHistoryOptions.addWidget(self.lytSymmetryMode)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frmHistoryOptions.addItem(spacerItem4)
        self.lytSymmetryOptions = QtWidgets.QGroupBox(self.frmHistory)
        self.lytSymmetryOptions.setObjectName("lytSymmetryOptions")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lytSymmetryOptions)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chkLinear = QtWidgets.QCheckBox(self.lytSymmetryOptions)
        self.chkLinear.setChecked(True)
        self.chkLinear.setObjectName("chkLinear")
        self.verticalLayout_3.addWidget(self.chkLinear)
        self.chkMarker = QtWidgets.QCheckBox(self.lytSymmetryOptions)
        self.chkMarker.setObjectName("chkMarker")
        self.verticalLayout_3.addWidget(self.chkMarker)
        self.btnPlayHistory = QtWidgets.QPushButton(self.lytSymmetryOptions)
        self.btnPlayHistory.setObjectName("btnPlayHistory")
        self.verticalLayout_3.addWidget(self.btnPlayHistory)
        self.lytSpeed = QtWidgets.QHBoxLayout()
        self.lytSpeed.setObjectName("lytSpeed")
        self.lblAnimSpeed = QtWidgets.QLabel(self.lytSymmetryOptions)
        self.lblAnimSpeed.setObjectName("lblAnimSpeed")
        self.lytSpeed.addWidget(self.lblAnimSpeed)
        self.spnAnimSpeed = QtWidgets.QSpinBox(self.lytSymmetryOptions)
        self.spnAnimSpeed.setMinimum(1)
        self.spnAnimSpeed.setMaximum(100)
        self.spnAnimSpeed.setObjectName("spnAnimSpeed")
        self.lytSpeed.addWidget(self.spnAnimSpeed)
        self.verticalLayout_3.addLayout(self.lytSpeed)
        self.frmHistoryOptions.addWidget(self.lytSymmetryOptions)
        self.gridLayout_2.addLayout(self.frmHistoryOptions, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frmHistory, 0, 0, 1, 1)
        self.frmSymmetrySlider = QtWidgets.QFrame(self.dckContainerHistory)
        self.frmSymmetrySlider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmSymmetrySlider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmSymmetrySlider.setObjectName("frmSymmetrySlider")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmSymmetrySlider)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSymmetryMode = QtWidgets.QLabel(self.frmSymmetrySlider)
        self.lblSymmetryMode.setObjectName("lblSymmetryMode")
        self.horizontalLayout.addWidget(self.lblSymmetryMode)
        self.sldSymmetry = QtWidgets.QSlider(self.frmSymmetrySlider)
        self.sldSymmetry.setOrientation(QtCore.Qt.Horizontal)
        self.sldSymmetry.setObjectName("sldSymmetry")
        self.horizontalLayout.addWidget(self.sldSymmetry)
        self.sldSymmetryValue = QtWidgets.QLabel(self.frmSymmetrySlider)
        self.sldSymmetryValue.setText("")
        self.sldSymmetryValue.setObjectName("sldSymmetryValue")
        self.horizontalLayout.addWidget(self.sldSymmetryValue)
        self.gridLayout_3.addWidget(self.frmSymmetrySlider, 1, 0, 1, 1)
        self.dckHistoryPlot.setWidget(self.dckContainerHistory)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dckHistoryPlot)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setEnabled(False)
        self.action_Open.setShortcut("")
        self.action_Open.setObjectName("action_Open")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.action_History_Plot = QtWidgets.QAction(MainWindow)
        self.action_History_Plot.setCheckable(True)
        self.action_History_Plot.setChecked(False)
        self.action_History_Plot.setObjectName("action_History_Plot")
        self.dckHistoryPlot.raise_()
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.actionE_xit)
        self.menu_View.addAction(self.action_History_Plot)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.sldVValue.setBuddy(self.sldV)
        self.lblV.setBuddy(self.sldV)
        self.sldvValue.setBuddy(self.sldv)
        self.lblv.setBuddy(self.sldv)
        self.sldPhaseValue.setBuddy(self.sldPhase)
        self.lblPhase.setBuddy(self.sldPhase)

        self.retranslateUi(MainWindow)
        self.action_History_Plot.toggled['bool'].connect(self.dckHistoryPlot.setVisible)
        self.dckHistoryPlot.visibilityChanged['bool'].connect(self.action_History_Plot.setChecked)
        self.actionE_xit.triggered.connect(MainWindow.close)
        self.sldSymmetry.valueChanged['int'].connect(self.sldSymmetryValue.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skyrme Explorer"))
        self.grpNavInfo.setTitle(_translate("MainWindow", "Sim. Parameters"))
        self.lblV.setText(_translate("MainWindow", "V"))
        self.lblv.setText(_translate("MainWindow", "v"))
        self.lblPhase.setText(_translate("MainWindow", "ϕ"))
        self.grpRender.setTitle(_translate("MainWindow", "Render parameters"))
        self.chkLogScale.setText(_translate("MainWindow", "Log scale"))
        self.label.setText(_translate("MainWindow", "log(eps)="))
        self.label_2.setText(_translate("MainWindow", "Img. width:"))
        self.grpNavInfoOptions.setTitle(_translate("MainWindow", "Options"))
        self.chkSaveImage.setText(_translate("MainWindow", "Save Image"))
        self.chkRegenImg.setText(_translate("MainWindow", "Regen. image"))
        self.chkRegen.setText(_translate("MainWindow", "Regen Sim."))
        self.chkPreferImage.setText(_translate("MainWindow", "Prefer Image"))
        self.chkAutoLoad.setText(_translate("MainWindow", "Auto-load"))
        self.btnGenerate.setText(_translate("MainWindow", "Generate"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.dckHistoryPlot.setWindowTitle(_translate("MainWindow", "History Plot"))
        self.lytSymmetryMode.setTitle(_translate("MainWindow", "Mode"))
        self.rbtT.setText(_translate("MainWindow", "Fixed τ"))
        self.rbtX.setText(_translate("MainWindow", "Fixed x"))
        self.lytSymmetryOptions.setTitle(_translate("MainWindow", "Options"))
        self.chkLinear.setText(_translate("MainWindow", "Linear"))
        self.chkMarker.setText(_translate("MainWindow", "Show Marker"))
        self.btnPlayHistory.setText(_translate("MainWindow", "▶"))
        self.lblAnimSpeed.setText(_translate("MainWindow", "Speed"))
        self.lblSymmetryMode.setText(_translate("MainWindow", "τ"))
        self.action_Open.setText(_translate("MainWindow", "&Open Directory"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionE_xit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_History_Plot.setText(_translate("MainWindow", "&History Plot"))
        self.action_History_Plot.setToolTip(_translate("MainWindow", "History Plot"))
        self.action_History_Plot.setShortcut(_translate("MainWindow", "Ctrl+H"))

from qmatplotlib import QMatplotlibHistory, QParamPlot, QSimPlot
