#!/usr/bin/env python
# -*- coding: utf-8 -*-

# PRINT OSC HEADER

import sys
from open_sim import ShowHeaderOfOscFile

if __name__ == '__main__':

    filename = sys.argv[1]

    ShowHeaderOfOscFile(filename)


